# Generated by Django 5.0.3 on 2024-03-18 02:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userregistration_delete_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRegistration",
        ),
    ]
